title: 웹페이지
author:
  name: 홍길동
  email: genius721@github.io
description: > # this means to ignore newlines until "show_excerpts:"
  Jekyll 정적 페이지 입니다.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%F %T %z"

  # generate social links in footer
  social_links:
    # twitter: genius721
    github:  genius721
    # devto: genius721
    # dribbble: genius721
    # facebook: genius721
    # flickr:   genius721
    # instagram: genius721
    linkedin: genius721
    # pinterest: genius721
    # youtube: genius721
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: genius721
    # googleplus: +genius721
    # microdotblog: genius721
    # keybase: genius721

    # Mastodon instances
    # mastodon:
    # - username: genius721
    #   instance: example.com
    # - username: genius721
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: genius721
    #   instance: example.com
    # - username: genius721
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
 # Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: genius-5

url: "https://genius721.github.io"
